FROM mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04

USER root

# Install custom packages
RUN apt-get update && apt-get install -y dos2unix

RUN mkdir -p /usr/config
WORKDIR /usr/config

COPY db.entrypoint.sh .
COPY db.autobackup.sh .

RUN dos2unix db.entrypoint.sh
RUN dos2unix db.autobackup.sh

EXPOSE 1433

CMD [ "/bin/bash", "db.entrypoint.sh" ]
